version: "3"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - .:/opt/docker-quarkus-mysql
      - /opt/docker-quarkus-mysql
      - maven-repo:/root/.m2
    links:
      - db
    networks:
      - default
      - projects

  db:
    image: mysql:8.0.16
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kirkdb
      MYSQL_USER: kirk
      MYSQL_PASSWORD: kirk-pass
    ports:
      - "3307:3306"
    command: --max-connections=1024
    networks:
      default:
      projects:
        aliases:
          - projects-kirk.mysql
networks:
  default:
  projects:
    external: true
